language: php
php:
    - 7.0
    - 7.1
    - 7.2
    - nightly
    - hhvm

env:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"

matrix:
    allow_failures:
        - php: hhvm
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

install:
    - if [[ "$DEPENDENCIES" = 'high' ]]; then composer update; fi
    - if [[ "$DEPENDENCIES" = 'low' ]]; then composer update --prefer-lowest; fi
    - composer require php-coveralls/php-coveralls '^2.0' --dev

script:
    - php vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
    - php vendor/bin/php-coveralls -v

notifications:
    email: false
